language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t piyapan/simple-ci-cd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true piyapan/simple-ci-cd-react npm run test