language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ZPiyapanZ/simple-ci-cd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ZPiyapanZ/simple-ci-cd-react npm run test